version: '3.7'
services:
  bitwarden:
    image: bitwardenrs/server:1.17.0-alpine
    container_name: bitwarden
    restart: always
    volumes:
      - ./bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true'  # Required to use websockets
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
    expose:                      # set true first for setup, then recreate container with false
      - 80
      - 3012
    networks:
      - nginx

networks:
  nginx:
    external: true
