version: '3.7'
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /path/to/nginx/data/certbot/conf:/etc/letsencrypt
      - /path/to/nginx/data/certbot/www:/var/www/certbot