version: '3.7'

services:
  archiveteam:
    container_name: archiveteam
    image: archiveteam/warrior-dockerfile
    ports:
      - 8001:8001
    restart: always
    networks:
      - dist
    dns:
      - 116.202.176.26
      - 84.200.69.80
      - 84.200.70.40
      - 88.198.91.187
      - 95.216.181.228

networks:
  dist:
    external: true
