version: '3.7'
services:
  pihole-exporter:
    container_name: pihole-exporter
    image: 'ekofr/pihole-exporter:0.0.10'
    restart: always
    environment:
      - PIHOLE_HOSTNAME=HOSTNAMEORIPADDRESS
      - PIHOLE_PASSWORD=PASSWORD
      - INTERVAL=30s
      - PORT=9617
    expose:
      - 9617
    networks:
      - nginx
    labels:
      org.label-schema.group: "monitoring"

networks:
  nginx:
    external: true
