version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.19.5-alpine
    restart: always
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./credentials/node-exporter.htpasswd:/etc/nginx/basic_auth/node-exporter.htpasswd
      - ./credentials/cadvisor.htpasswd:/etc/nginx/basic_auth/cadvisor.htpasswd
      - ./credentials/nginxexporter.htpasswd:/etc/nginx/basic_auth/nginxexporter.htpasswd
      - ./credentials/processexporter.htpasswd:/etc/nginx/basic_auth/processexporter.htpasswd
      - ./credentials/pushgateway.htpasswd:/etc/nginx/basic_auth/pushgateway.htpasswd
      - ./credentials/prometheus.htpasswd:/etc/nginx/basic_auth/prometheus.htpasswd
      - ./credentials/logstash.htpasswd:/etc/nginx/basic_auth/logstash.htpasswd
      - ./credentials/elasticsearch.htpasswd:/etc/nginx/basic_auth/elasticsearch.htpasswd
      - ./credentials/kibana.htpasswd:/etc/nginx/basic_auth/kibana.htpasswd
      - /path/to/nginx/data/certbot/conf:/etc/letsencrypt
      - /path/to/nginx/data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx

networks:
  nginx:
    external: true
