{
 "title": "Nginx",
 "description": "Nginx exporter metrics",
 "tags": [ "nginx" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "active" },
    { "expr": "nginx_connections_reading", "legendFormat": "reading" },
    { "expr": "nginx_connections_writing", "legendFormat": "writing" },
    { "expr": "nginx_connections_waiting", "legendFormat": "waiting" }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{job=\"nginx\"}[5m])",
     "legendFormat": "requests"
    }
   ]
  }
 ]
}