version: '3.7'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    expose:
      - 9000
    volumes:
      - /docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx
networks:
  nginx:
    external: true
