{
 "title": "Pihole",
 "tags": [ "external" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_status{hostname=\"chip\",instance=\"pihole-exporter:9617\",job=\"pihole\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Blocked domains",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{hostname=\"chip\",instance=\"pihole-exporter:9617\",job=\"pihole\"}"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pihole_unique_domains{hostname=\"chip\",instance=\"pihole-exporter:9617\",job=\"pihole\"}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "DNS queries of all types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_dns_queries_all_types", "legendFormat": "Total queries" }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 3 },
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "DNS query types",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Ads blocked today",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_ads_blocked_today", "legendFormat": "Total ads blocked" }
   ]
  },
  {
   "title": "Replies by type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_reply", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "% of ads blocked" }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pihole_forward_destinations", "legendFormat": "{{ destination }}" }
   ]
  },
  {
   "title": "Queries cached / forwarded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_queries_cached", "legendFormat": "Queries cached" },
    { "expr": "pihole_queries_forwarded", "legendFormat": "Queries forwarded" }
   ]
  },
  {
   "title": "Top ads",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{ domain }}" }
   ]
  }
 ]
}