# filebeat.yml

filebeat.inputs:
  - type: log
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
     host: "unix:///var/run/docker.sock"
  - decode_json_fields:
     fields: ["message"]
     target: "json"
     overwrite_keys: true

output.logstash:
  hosts: ["logstash"]

logging.to_stderr: true
logging.json: true
