version: '3.7'

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SERVERURL=server.example.com
      - SERVERPORT=51820
      - PEERS=1                       # how many peers config will be created
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=192.168.178.0/24   # will allow client to access local network
    volumes:
      - /path/to/config:/config       # will contain the peer config file & the QR code
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - nginx

networks:
  nginx:
    external: true
