name: CI
on: [push]
jobs:
  yamllinter:
    runs-on: ubuntu-latest
    steps:
      - name: set up git repository
        uses: actions/checkout@master
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@master
        with:
          config_file: .yamllint.yml

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: set up git repository
        uses: actions/checkout@v1
      - name: Lint check
        uses: azohra/shell-linter@v0.2.0
