name: CI
on: [push]
jobs:
  yamllinter:
    runs-on: ubuntu-latest
    steps:
      - name: set up git repository
        uses: actions/checkout@master
      - name: lint all yaml files
        uses: ibiqlik/action-yamllint@master
        with:
          config_file: .yamllint.yml

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: set up git repository
        uses: actions/checkout@v1
      - name: lint all shell script
        uses: azohra/shell-linter@latest
